Solicitar certificación
Harckh/certification-repo pull request #12
Opened 2022-09-06 13:11 UTC by ChrisRojano08

2022-09-06 15:00 UTC, Harckh commented on cursos.json
> +                        "rfc": "ROJC010403ARA",
Editar el valor de rfc por el establecido en tu perfil de la plataforma de Task Manger (Bugs).
"ROJC010403"

2022-09-06 15:02 UTC, Harckh requested changes
Atender los comentarios.

2022-09-06 15:02 UTC, Harckh commented on cursos.json
> +                        "evidencia": "https://drive.google.com/drive/folders/1uVbii8ocSap3z_3ucur0qG2b8HNYMSDr?usp=sharing",
Realizar nuevamente la prueba, obtuviste una calificación de 4/5.

2022-09-07 13:15 UTC, ChrisRojano08 commented on cursos.json
> +                        "evidencia": "https://drive.google.com/drive/folders/1uVbii8ocSap3z_3ucur0qG2b8HNYMSDr?usp=sharing",
chale pero si eso es un 8 UnU

2022-09-07 13:16 UTC, ChrisRojano08 commented on cursos.json
> +                        "rfc": "ROJC010403ARA",
oks

2022-09-08 16:51 UTC, Harckh approved these changes

2022-09-08 16:51 UTC, merged